In [33]:
import numpy as np


In [34]:
arrae_n2=np.array([1,2,"3"], dtype=np.float16)
print(arrae_n2)
print(type(arrae_n2))
print(type(arrae_n2[2]))

[1. 2. 3.]
<class 'numpy.ndarray'>
<class 'numpy.float16'>


# 2. np.arange(start,stop,step)


In [35]:
print(np.arange(5))
print(np.arange(1,10,2))

[0 1 2 3 4]
[1 3 5 7 9]


In [36]:
np_arrange =np.arange(1,10,2)
print(type(np_arrange))

<class 'numpy.ndarray'>


# np.linspace(start,stop,num=x)

In [41]:
np_linespace= np.linspace(0,100,10)
print(np_linespace)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [44]:
for i in np.linspace(1,10,10):
    print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


# np.zero create array of zero

In [47]:
npz_3d=np.zeros((5,5,5))
print(npz_3d)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [ ]:
import numpy 
